# Landau-only sweep example.
#
# Use this file when the experiment route is already acceptable and you only
# want to change the Landau polynomial coefficients across runs.

include(joinpath(@__DIR__, "parallel_sweep_example2.jl"))

###############################################################################
# Base parameters shared by all Landau variants
###############################################################################

landau_base = MT.ManuscriptParams(;
    outdir = raw"D:\Code\data\Manuscript\Landau_sweep_demo",
    xL = 40,
    yL = 40,
    zL = 10,
    JIsing = 1,
    Scale = 1.0,
    Screening = 0.01,
    Temp = 0.5f0,
    Temp_aneal = 3f0,
    time_fctr = 1.0,
    Steps_1 = 6000,
    Amp1 = 3.0,
    nrepeats = 2,
    landau_mode = :coupled,
)

###############################################################################
# Helpers for making coefficient sets
###############################################################################

function coeffs_246(a, c)
    b = -(a + 3c) / 2
    return Dict(2 => a, 4 => b, 6 => c)
end

function coeffs_from_stationary_abs_positions(abs_positions; K = 1.0)
    length(abs_positions) == 4 || error("Need exactly four positive extrema positions for a 10th-order even polynomial.")

    roots = Float64.(abs_positions) .^ 2
    poly = [1.0]

    for r in roots
        newpoly = zeros(Float64, length(poly) + 1)
        for i in eachindex(poly)
            newpoly[i] += -r * poly[i]
            newpoly[i + 1] += poly[i]
        end
        poly = newpoly
    end

    q0, q1, q2, q3, q4 = K .* poly
    return Dict(
        2 => q0 / 2,
        4 => q1 / 4,
        6 => q2 / 6,
        8 => q3 / 8,
        10 => q4 / 10,
    )
end

###############################################################################
# Example A: manually list a few Landau shapes
###############################################################################

function listed_landau_paramsets(base)
    variants = [
        (name = "default_246", coeffs = coeffs_246(-2.0, 10.0)),

        # Stronger sixth order, b is chosen from b = -(a + 3c) / 2.
        (name = "strong_c_246", coeffs = coeffs_246(-2.0, 16.0)),

        # Explicit 2/4/6/8/10 polynomial from your Landau shape exploration.
        (name = "ten_order_many_bends", coeffs = Dict(
            2 => 6.012006,
            4 => -16.255578,
            6 => 16.73805,
            8 => -7.42875,
            10 => 1.2,
        )),

        # Same idea, generated by choosing extrema positions directly:
        # P = 0 is lowest, +/-1 are local minima, and there are extra bends.
        (name = "stationary_positions", coeffs = coeffs_from_stationary_abs_positions(
            [0.55, 1.0, 1.30, 1.40];
            K = 12.0,
        )),
    ]

    return [
        MT.update_params(
            base;
            landau_mode = :coupled,
            landau_coeffs = item.coeffs,
            outdir = joinpath(base.outdir, item.name),
        )
        for item in variants
    ]
end

###############################################################################
# Example B: grid sweep over a and c in a*P^2 + b*P^4 + c*P^6
###############################################################################

function ac_grid_landau_paramsets(base)
    a_values = (-1.0, -2.0, -3.0)
    c_values = (6.0, 10.0, 14.0)

    return [
        MT.update_params(
            base;
            landau_mode = :coupled,
            landau_coeffs = coeffs_246(a, c),
            outdir = joinpath(base.outdir, "a=$(a)_c=$(c)"),
        )
        for a in a_values
        for c in c_values
    ]
end

###############################################################################
# Example C: independent localpotential mode
###############################################################################

function independent_landau_paramsets(base)
    variants = [
        (name = "independent_246", coeffs = Dict(2 => -2.0, 4 => 14.0, 6 => 10.0)),
        (name = "independent_2468", coeffs = Dict(2 => -2.0, 4 => 14.0, 6 => 10.0, 8 => -1.0)),
        (name = "equal minima", coeffs = Dict(2  => 1.7850625, 4  => -12.020125, 6  => 28.6850625, 8  => -28.45, 10 => 10.0)),
    ]

    return [
        MT.update_params(
            base;
            landau_mode = :independent,
            landau_coeffs = item.coeffs,
            outdir = joinpath(base.outdir, item.name),
        )
        for item in variants
    ]
end

###############################################################################
# Running the sweep
###############################################################################

function run_landau_sweep(paramsets; max_inflight = 2, capture = false)
    println("Prepared $(length(paramsets)) Landau runs.")
    println("Running at most $(max_inflight) simulations at the same time.")
    println("Intermediate capture frames: ", capture ? "on" : "off")
    println("Output folders:")
    for p in paramsets
        println("  ", p.outdir)
    end

    return run_packaged_pulse_sweep_batched(paramsets; max_inflight, capture)
end

function print_saved_outputs(results)
    for item in results
        println()
        println("Run output folder: ", item.params.outdir)
        println("Saved xlsx: ", item.paths.xlsx_path)
        println("Saved Pr distribution: ", item.paths.png_path_dist)
        println("Saved Landau curve: ", item.paths.png_path_landau)
        println("Saved Landau zoom [-1,1]: ", item.paths.png_path_landau_zoom)
        println("Saved final state CSV standard: ", item.paths.csv_path_state)
        println("Saved final state CSV Excel EU: ", item.paths.csv_path_state_eu)
        println("Saved final state figure: ", item.paths.png_path_state)
        !isnothing(item.paths.png_path_pv) && println("Saved P-V: ", item.paths.png_path_pv)
        !isnothing(item.paths.png_path_pt) && println("Saved P-T: ", item.paths.png_path_pt)
    end
    return results
end

function run_default_landau_sweep(; max_inflight = 2, capture = false)
    paramsets = listed_landau_paramsets(landau_base)
    results = run_landau_sweep(paramsets; max_inflight, capture)
    print_saved_outputs(results)

    return results
end

function run_ac_grid_landau_sweep(; max_inflight = 2, capture = false)
    paramsets = ac_grid_landau_paramsets(landau_base)
    results = run_landau_sweep(paramsets; max_inflight, capture)
    print_saved_outputs(results)
    return results
end

function run_independent_landau_sweep(; max_inflight = 2, capture = false)
    paramsets = independent_landau_paramsets(landau_base)
    results = run_landau_sweep(paramsets; max_inflight, capture)
    print_saved_outputs(results)
    return results
end

if abspath(PROGRAM_FILE) == @__FILE__
    ## Direct "Run File" enters here.

    # run_default_landau_sweep(; max_inflight = 4, capture = false)
    # run_ac_grid_landau_sweep(; max_inflight = 4, capture = false)
    run_independent_landau_sweep(; max_inflight = 4, capture = false)
end
