"""
Turn `@init((; ...))` into a keyword assignment `_init = (; ...)`.

This is primarily meant for the bootstrap call style generated by `@ProcessAlgorithm`,
for example:

```julia
MyAlgo(input; @init((; n = 10)))
```
"""
macro init(ex)
    return Expr(:kw, :_init, esc(ex))
end

"""
Turn `@input((; ...))` into a keyword assignment `_init = (; ...)`.

Compatibility alias for older macro call sites that used the singular form.
"""
macro input(ex)
    return Expr(:kw, :_init, esc(ex))
end

"""
Turn `@inputs((; ...))` into a keyword assignment `_init = (; ...)`.

This is the clearer public alias for the init-time input declarations consumed by
`@ProcessAlgorithm`.
"""
macro inputs(ex)
    return Expr(:kw, :_init, esc(ex))
end

_pa_is_macrocall(ex, names::Symbol...) =
    ex isa Expr && ex.head == :macrocall && any(name -> ex.args[1] == name, names)

_pa_is_inputs_macro(ex) = _pa_is_macrocall(ex, Symbol("@init"), Symbol("@input"), Symbol("@inputs"))
_pa_macro_args(ex) = [arg for arg in ex.args[2:end] if !(arg isa LineNumberNode)]

function _pa_unwrap_where(ex)
    where_params = Any[]
    while ex isa Expr && ex.head == :where
        push!(where_params, ex.args[2])
        ex = ex.args[1]
    end
    return ex, reverse(where_params)
end

function _pa_rewrap_where(ex, where_params)
    for param in where_params
        ex = Expr(:where, ex, param)
    end
    return ex
end

function _pa_binding_parts(ex)
    if ex isa Symbol
        return ex, nothing
    elseif ex isa Expr && ex.head == :(::)
        return ex.args[1], ex.args[2]
    end
    error("Unsupported argument declaration: $ex")
end

_pa_binding_expr(name::Symbol, typeexpr) = isnothing(typeexpr) ? name : Expr(:(::), name, typeexpr)

function _pa_parse_kw_decl(ex)
    @assert ex isa Expr && ex.head == :kw "Expected keyword declaration, got $ex"
    name, typeexpr = _pa_binding_parts(ex.args[1])
    return (; name, typeexpr, default = ex.args[2])
end

function _pa_parse_init_tuple(ex)
    ex isa Expr && ex.head == :tuple || error("@input/@inputs/@init expects a named tuple style payload, got $ex")
    !isempty(ex.args) || return NamedTuple[]
    params = ex.args[1]
    params isa Expr && params.head == :parameters || error("@input/@inputs/@init expects a named tuple style payload, got $ex")

    fields = NamedTuple[]
    for arg in params.args
        if arg isa Expr && arg.head == :kw
            name, typeexpr = _pa_binding_parts(arg.args[1])
            push!(fields, (; name, typeexpr, default = arg.args[2], required = false))
        else
            name, typeexpr = _pa_binding_parts(arg)
            push!(fields, (; name, typeexpr, default = nothing, required = true))
        end
    end
    return fields
end

function _pa_parse_managed_arg(ex)
    if ex isa Expr && ex.head == :(=)
        name, typeexpr = _pa_binding_parts(ex.args[1])
        return (; kind = :managed, name, typeexpr, default = ex.args[2], has_default = true, capture_input = true)
    end
    name, typeexpr = _pa_binding_parts(ex)
    return (; kind = :managed, name, typeexpr, default = nothing, has_default = false, capture_input = true)
end

function _pa_parse_positional_arg(ex)
    if _pa_is_macrocall(ex, Symbol("@managed"))
        return map(_pa_parse_managed_arg, _pa_macro_args(ex))
    elseif ex isa Expr && ex.head == :(=)
        error("Only @managed positional arguments may have defaults, got $ex")
    else
        name, typeexpr = _pa_binding_parts(ex)
        return [(; kind = :plain, name, typeexpr, default = nothing, has_default = false, capture_input = false)]
    end
end

function _pa_new_parse_signature(call_ex)
    call_ex, where_params = _pa_unwrap_where(call_ex)
    call_ex isa Expr && call_ex.head == :call || error("@ProcessAlgorithm expects a function definition")

    fname = call_ex.args[1]
    args = call_ex.args[2:end]
    params = nothing
    if !isempty(args) && args[1] isa Expr && args[1].head == :parameters
        params = args[1]
        args = args[2:end]
    end

    positional = Any[]
    for arg in args
        append!(positional, _pa_parse_positional_arg(arg))
    end
    plain_pos = filter(x -> x.kind == :plain, positional)
    managed_pos = filter(x -> x.kind == :managed, positional)

    normal_kwargs = NamedTuple[]
    input_fields = NamedTuple[]
    if !isnothing(params)
        for (idx, arg) in enumerate(params.args)
            if _pa_is_inputs_macro(arg)
                idx == length(params.args) || error("@input/@inputs/@init must be the last keyword-like argument in @ProcessAlgorithm")
                isempty(input_fields) || error("Only one @input/@inputs/@init block is allowed in @ProcessAlgorithm")
                input_fields = _pa_parse_init_tuple(arg.args[end])
            else
                push!(normal_kwargs, _pa_parse_kw_decl(arg))
            end
        end
    end

    return (; fname, positional, plain_pos, managed_pos, normal_kwargs, input_fields, where_params)
end

_pa_local_get_expr(ctx, name::Symbol, default) = :(get($ctx, $(QuoteNode(name)), $default))

function _pa_required_get_expr(ctx, name::Symbol)
    quote
        if !haskey($ctx, $(QuoteNode(name)))
            error("Missing required input $(string($(QuoteNode(name))))")
        end
        getproperty($ctx, $(QuoteNode(name)))
    end
end

_pa_typed_assignment(name::Symbol, typeexpr, value_expr) = :(local $name = $value_expr)

function _pa_input_assignment_exprs(field, ctxsym, tempsym; bind_public = true)
    getexpr = field.required ? _pa_required_get_expr(ctxsym, field.name) : _pa_local_get_expr(ctxsym, field.name, field.default)
    exprs = Any[:(local $tempsym = $getexpr)]
    bind_public && push!(exprs, _pa_typed_assignment(field.name, field.typeexpr, tempsym))
    return exprs
end

function _pa_managed_assignment(field, input_temps, ctxsym)
    value_expr = if field.has_default
        field.default
    elseif haskey(input_temps, field.name)
        input_temps[field.name]
    else
        _pa_required_get_expr(ctxsym, field.name)
    end
    return _pa_typed_assignment(field.name, field.typeexpr, value_expr)
end

function _pa_runtime_kw_assignment(field, ctxsym)
    getexpr = _pa_local_get_expr(ctxsym, field.name, field.default)
    return _pa_typed_assignment(field.name, field.typeexpr, getexpr)
end

function _pa_runtime_pos_assignment(field, ctxsym)
    return _pa_typed_assignment(field.name, field.typeexpr, :(getproperty($ctxsym, $(QuoteNode(field.name)))))
end

"""
    @ProcessAlgorithm function Name(...)
        ...
    end

Define a `ProcessAlgorithm` from a function-like signature.

The macro splits the signature into three groups:

1. Plain positional arguments:
   Runtime values read from the process context during `Processes.step!`.
2. `@managed(...)` positional arguments:
   Local algorithm state created during `Processes.init` and then read back from the
   algorithm's own subcontext during `Processes.step!`.
3. Normal keyword arguments:
   Runtime keyword-style values looked up from the context during `Processes.step!`, with
   the declared default used when the key is missing.

An optional trailing `@input((; ...))`, `@inputs((; ...))`, or `@init((; ...))` block declares
init-time inputs. These are only available while building managed state and in the bootstrap
call form; they are not automatically runtime arguments unless you also capture them into
managed state.

# Supported signature forms

The macro accepts normal function signatures and `where` signatures:

```julia
@ProcessAlgorithm function Accumulate(x)
    return (; x = x + 1)
end

@ProcessAlgorithm function resetgraph!(isinggraph::G) where G
    resetstate!(isinggraph)
    return
end
```

# Positional parsing rules

Plain positional arguments:

```julia
@ProcessAlgorithm function F(a, b)
    ...
end
```

These are treated as runtime values and are looked up from the context inside `Processes.step!`.

Managed positional arguments:

```julia
@ProcessAlgorithm function F(
    a,
    @managed(state = 0.0),
    @managed(cache),
    @managed(buffer = zeros(n), metric = 0.0);
    @inputs((; n = 8))
)
    ...
end
```

The managed forms mean:

- `@managed(name)`:
  create a managed local called `name` by reading `name` from the init context.
- `@managed(name = expr)`:
  create a managed local called `name` by evaluating `expr` during `Processes.init`.
- `@managed(a, b = expr, c = expr2)`:
  expand to multiple managed locals in the written order.

Managed initializer expressions run during `Processes.init`, so they may refer to:

- init-time inputs declared by `@input/@inputs/@init`
- earlier managed locals in the same generated init block
- plain Julia globals/functions in scope

They do not read plain runtime positional arguments from `step!`.

# Keyword parsing rules

Regular keyword arguments:

```julia
@ProcessAlgorithm function F(a; gain = 1.0, offset::Float64 = 0.0)
    ...
end
```

These are runtime keyword-style values. During `Processes.step!`, the macro reads them from the
context with `get(context, :name, default)`.

Init-time input block:

```julia
@ProcessAlgorithm function F(
    a,
    @managed(scale = scale0);
    gain = 1.0,
    @inputs((; scale0::Float64 = 2.0, n::Int))
)
    ...
end
```

Rules:

- only one of `@input`, `@inputs`, or `@init` is allowed
- it must be the last keyword-like entry in the signature
- entries may be required (`n`) or defaulted (`scale0 = 2.0`)

# What the macro defines

For a declaration like:

```julia
@ProcessAlgorithm function MyAlgo(...)
    body
end
```

the macro generates:

- `struct MyAlgo <: Processes.ProcessAlgorithm end`
- a hidden implementation function that contains `body`
- a public bootstrap call `MyAlgo(...)` that can be called directly
- `Processes.init(::MyAlgo, context)` to build the managed local subcontext
- `Processes.step!(::MyAlgo, context)` to read runtime values and call the hidden implementation

# User entrypoints

There are three main ways users interact with a macro-generated algorithm:

1. Direct/bootstrap call:

```julia
MyAlgo(a; @inputs((; n = 4)))
```

This evaluates the managed init path immediately and then calls the generated implementation.

2. Process init hook:

```julia
Processes.init(MyAlgo(), context)
```

This reads the declared init inputs from `context` and returns the managed local named tuple.

3. Process step hook:

```julia
Processes.step!(MyAlgo(), context)
```

This reads plain positional and runtime keyword arguments from `context`, reads managed values
from the algorithm subcontext, and forwards everything to the generated implementation.

# Type annotations and `where`

Argument type annotations are preserved on the generated public call signatures and on the hidden
implementation function. `where` clauses are also preserved there.

The generated `Processes.init` and `Processes.step!` methods currently extract values from the
context into local bindings before calling the typed implementation. That means the original
argument annotations still constrain the implementation entrypoint, but the context extraction
bindings themselves are intentionally kept simple and untyped.
"""
macro ProcessAlgorithm(ex)
    ex isa Expr && ex.head == :function || error("@ProcessAlgorithm expects a function definition")

    signature = _pa_new_parse_signature(ex.args[1])
    body = ex.args[2]

    fname = signature.fname
    impl_name = gensym(Symbol(fname, :_impl))
    input_temps = Dict(field.name => gensym(Symbol(field.name, :_input)) for field in signature.input_fields)

    positional_bindings = [_pa_binding_expr(arg.name, arg.typeexpr) for arg in signature.positional]
    plain_pos_bindings = [_pa_binding_expr(arg.name, arg.typeexpr) for arg in signature.plain_pos]
    kw_bindings = [Expr(:kw, _pa_binding_expr(kw.name, kw.typeexpr), kw.default) for kw in signature.normal_kwargs]

    impl_signature = Expr(:call, impl_name, positional_bindings...)
    if !isempty(kw_bindings)
        insert!(impl_signature.args, 2, Expr(:parameters, kw_bindings...))
    end
    impl_signature = _pa_rewrap_where(impl_signature, signature.where_params)

    impl_def = Expr(:function, impl_signature, body)

    public_piped_signature = Expr(:call, fname, positional_bindings...)
    piped_kw_bindings = copy(kw_bindings)
    push!(piped_kw_bindings, Expr(:kw, :_init, nothing))
    insert!(public_piped_signature.args, 2, Expr(:parameters, piped_kw_bindings...))
    public_piped_signature = _pa_rewrap_where(public_piped_signature, signature.where_params)
    piped_kw_forward = [Expr(:kw, kw.name, kw.name) for kw in signature.normal_kwargs]
    piped_def = Expr(:function, public_piped_signature, quote
            if !isnothing(_init)
                error("Cannot pass both managed positional arguments and @input/@inputs/@init values to $(string($fname))")
            end
            return $impl_name($(map(x -> x.name, signature.positional)...); $(piped_kw_forward...))
        end)

    bootstrap_signature = Expr(:call, fname, plain_pos_bindings...)
    bootstrap_kw_bindings = copy(kw_bindings)
    push!(bootstrap_kw_bindings, Expr(:kw, :_init, Expr(:tuple, Expr(:parameters))))
    insert!(bootstrap_signature.args, 2, Expr(:parameters, bootstrap_kw_bindings...))
    bootstrap_signature = _pa_rewrap_where(bootstrap_signature, signature.where_params)
    bootstrap_input_assignments = Any[]
    bootstrap_bound_names = Set{Symbol}(arg.name for arg in signature.plain_pos)
    union!(bootstrap_bound_names, (kw.name for kw in signature.normal_kwargs))
    for field in signature.input_fields
        bind_public = !(field.name in bootstrap_bound_names)
        append!(bootstrap_input_assignments, _pa_input_assignment_exprs(field, :_init, input_temps[field.name]; bind_public))
    end
    bootstrap_managed_assignments = [_pa_managed_assignment(field, input_temps, :_init) for field in signature.managed_pos]
    bootstrap_kw_forward = [Expr(:kw, kw.name, kw.name) for kw in signature.normal_kwargs]
    bootstrap_call_args = [arg.name for arg in signature.plain_pos]
    append!(bootstrap_call_args, [arg.name for arg in signature.managed_pos])
    bootstrap_def = Expr(:function, bootstrap_signature, quote
            $(bootstrap_input_assignments...)
            $(bootstrap_managed_assignments...)
            return $impl_name($(bootstrap_call_args...); $(bootstrap_kw_forward...))
        end)

    input_assignments = Any[]
    for field in signature.input_fields
        append!(input_assignments, _pa_input_assignment_exprs(field, :context, input_temps[field.name]))
    end
    managed_assignments = [_pa_managed_assignment(field, input_temps, :context) for field in signature.managed_pos]
    managed_tuple_expr = Expr(:tuple, Expr(:parameters, [Expr(:kw, field.name, field.name) for field in signature.managed_pos]...))
    init_def = quote
        function Processes.init(_algo::$fname, context::C) where {C <: Union{Processes.AbstractContext, NamedTuple}}
            $(input_assignments...)
            $(managed_assignments...)
            return $managed_tuple_expr
        end
    end

    step_pos_assignments = [_pa_runtime_pos_assignment(field, :context) for field in signature.positional]
    step_kw_assignments = [_pa_runtime_kw_assignment(field, :context) for field in signature.normal_kwargs]
    step_kw_forward = [Expr(:kw, kw.name, kw.name) for kw in signature.normal_kwargs]
    step_call_args = [arg.name for arg in signature.positional]
    step_def = quote
        function Processes.step!(_algo::$fname, context::C) where {C <: Union{Processes.AbstractContext, NamedTuple}}
            $(step_pos_assignments...)
            $(step_kw_assignments...)
            return $impl_name($(step_call_args...); $(step_kw_forward...))
        end
    end

    q = quote
        struct $fname <: Processes.ProcessAlgorithm end
        $impl_def
        $piped_def
        $bootstrap_def
        $init_def
        $step_def
    end
    # println(q)
    return esc(q)
end

export @ProcessAlgorithm, @init, @input, @inputs
