include("Functions.jl")
include("ShuffleVec.jl")
include("PreAlloc.jl")
include("Sparse.jl")
include("UnRef.jl")
include("PausableTimer.jl")
include("VecStructIterator.jl")
include("Observables.jl")
include("NamedTupleType.jl")
include("Kwargs.jl")
include("Rand.jl")
include("AverageCircular.jl")
include("Averages.jl")
include("CastVec.jl")
#TODO: Make module
include("Processes.jl")
