include("Utils.jl")
# include("WeightGenerator.jl")
include("UndirectedAdjacency/UndirectedAdjacency.jl")
include("SparseMatrixCSC/SparseMatrixCSC.jl")
include("WeightGenerators.jl")
include("PhysicalWeightGenerators.jl")
include("ConnectionGenerators.jl")
include("SparseAdj.jl")
include("AllToAllWeightGenerators.jl")
include("Connections.jl")
include("User.jl")
