include("Quadratic.jl")
include("Quartic.jl")
include("MagField.jl")
include("Ising.jl")
# include("ConstantHam.jl")
include("GaussianBernoulli.jl")
include("Clamping.jl")
include("DepolarisationField.jl")
include("Sextic.jl")
include("Coulomb.jl")