name: Update Processes Subtree

on:
  # Trigger when Processes.jl is updated
  repository_dispatch:
    types: [update-processes]
  
  # Manual trigger
  workflow_dispatch:
  
  # Weekly check (optional)
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC

jobs:
  update-subtree:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for subtree
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Check for Processes.jl updates
      id: check_updates
      run: |
        # Get current commit in subtree
        CURRENT_COMMIT=$(git log --oneline -1 --grep="git-subtree-dir: deps/Processes" --pretty=format:"%H" | head -1)
        if [ -z "$CURRENT_COMMIT" ]; then
          echo "No previous subtree found"
          echo "has_updates=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get the commit hash from the subtree merge commit
        SUBTREE_COMMIT=$(git log $CURRENT_COMMIT -1 --pretty=format:"%b" | grep "git-subtree-split:" | cut -d' ' -f2)
        
        # Check if there are new commits in Processes.jl
        git ls-remote https://github.com/f-ij/Processes.jl main > remote_commit.txt
        REMOTE_COMMIT=$(cut -f1 remote_commit.txt)
        
        if [ "$SUBTREE_COMMIT" != "$REMOTE_COMMIT" ]; then
          echo "Updates found: $SUBTREE_COMMIT -> $REMOTE_COMMIT"
          echo "has_updates=true" >> $GITHUB_OUTPUT
        else
          echo "No updates found"
          echo "has_updates=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Update subtree
      if: steps.check_updates.outputs.has_updates == 'true'
      run: |
        git subtree pull --prefix=deps/Processes https://github.com/f-ij/Processes.jl main --squash -m "chore: update Processes.jl subtree"
    
    - name: Push changes
      if: steps.check_updates.outputs.has_updates == 'true'
      run: |
        git push origin main
